<?php include __DIR__ . '/../template/header.php'; ?>

<h2>Auditlog</h2>
<form method="GET" action="audit_log.php" class="row g-2 mb-3">
    <div class="col-md-2"><label class="form-label" for="from">Von</label><input class="form-control" type="date" id="from" name="from" value="<?= htmlspecialchars($filters['from'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
    <div class="col-md-2"><label class="form-label" for="to">Bis</label><input class="form-control" type="date" id="to" name="to" value="<?= htmlspecialchars($filters['to'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
    <div class="col-md-3"><label class="form-label" for="action_filter">Aktion</label><input class="form-control" id="action_filter" name="action_filter" value="<?= htmlspecialchars($filters['action'] ?? '', ENT_QUOTES, 'UTF-8') ?>"></div>
    <div class="col-md-2"><label class="form-label" for="user_id">Benutzer-ID</label><input class="form-control" type="number" min="1" id="user_id" name="user_id" value="<?= htmlspecialchars((string) ($filters['user_id'] ?? ''), ENT_QUOTES, 'UTF-8') ?>"></div>
    <div class="col-md-2"><label class="form-label" for="result">Ergebnis</label><select class="form-select" id="result" name="result"><option value="">Alle</option><option value="success" <?= ($filters['result'] ?? '') === 'success' ? 'selected' : '' ?>>Erfolg</option><option value="failed" <?= ($filters['result'] ?? '') === 'failed' ? 'selected' : '' ?>>Fehler</option></select></div>
    <div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary" type="submit">Filtern</button></div>
</form>
<form method="POST" action="audit_log.php" class="mb-3"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars(generate_csrf_token(), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="from" value="<?= htmlspecialchars($filters['from'] ?? '', ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="to" value="<?= htmlspecialchars($filters['to'] ?? '', ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="action_filter" value="<?= htmlspecialchars($filters['action'] ?? '', ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="user_id" value="<?= htmlspecialchars((string) ($filters['user_id'] ?? ''), ENT_QUOTES, 'UTF-8') ?>"><input type="hidden" name="result" value="<?= htmlspecialchars($filters['result'] ?? '', ENT_QUOTES, 'UTF-8') ?>"><button class="btn btn-outline-secondary" type="submit" name="export_csv">CSV exportieren</button></form>

<div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>Zeit</th><th>Benutzer</th><th>Aktion</th><th>Ergebnis</th><th>Objekt</th><th>ID</th><th>Gerät</th><th>Request</th></tr></thead><tbody><?php foreach ($entries as $entry): ?><tr><td><?= htmlspecialchars($entry['created_at'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($entry['username'] ?? 'kiosk', ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($entry['action'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($entry['result'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($entry['entity_type'] ?? '', ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars((string) $entry['entity_id'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($entry['device_id'] ?? '', ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($entry['request_id'] ?? '', ENT_QUOTES, 'UTF-8') ?></td></tr><?php endforeach; ?></tbody></table></div>

<?php include __DIR__ . '/../template/footer.php'; ?>
